name: CI
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        native_ext: ['', '1']
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Run tests
      env:
        RBENV_NATIVE_EXT: ${{ matrix.native_ext }}
      run: npm cit
