name: Release
on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1.4
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: nodenv
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_BUMP_PR_COMMITTER_TOKEN }}
