name: Release
on: { push: { tags: 'v[0-9]+.[0-9]+.[0-9]+' } }

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: script/release-notes | tee relnotes.txt
      - uses: jasonkarns/create-release
        with:
          body_file: relnotes.txt

  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: nodenv
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_BUMP_PR_COMMITTER_TOKEN }}

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
