name: Release
on:
  push:
    tags: 'v*'

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: script/release-notes | tee relnotes.txt
      - id: relname
        run: echo "::set-output name=version::${TAG_REF##*/v}"
        env:
          TAG_REF: ${{ github.ref }}

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: nodenv ${{ steps.relname.outputs.version }}
          body_path: relnotes.txt

  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1.4
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: nodenv
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_BUMP_PR_COMMITTER_TOKEN }}
